layout_spectrum: 0.2361702
name: 'Southern Edge Glass & Rock Etching'
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.6138774
color:
  brandStrength: 0.4574468
  lightness: 0.7851064
  saturation: 0.09432261
  rhythmicContrast: 1
  brandColors:
    - '#BCBBB5'
    - '#9A5339'
    - '#303138'
    - '#FBFBFF'
    - '#6DB5F1'
