layout_spectrum: 0.9234043
name: 'Southern Edge Glass & Rock Etching'
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.6138774
color:
  brandStrength: 0.3651389
  lightness: 0.7851064
  saturation: 0.09432261
  rhythmicContrast: 0.9804882
  brandColors:
    - '#1F050D'
    - '#761720'
    - '#9A4143'
    - '#FFFAE9'
    - '#BD916E'
