layout_spectrum: 0.2361702
name: 'Southern Edge Glass & Rock Etching'
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
color:
  brandStrength: 1
  lightness: 0.7851064
  saturation: 0.09432261
  rhythmicContrast: 0.9804882
  brandColors:
    - '#0C0F1F'
    - '#FBFFFF'
    - '#ABB4AC'
    - '#C5E7F3'
    - '#023AC6'
typography_spectrum: 0.6138774
